# Generated by Django 5.1.2 on 2024-11-03 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapyApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='amazonproduct',
            table='amazon_products',
        ),
    ]
